#!/usr/bin/python
import sys
import argparse
import meshtastic
import meshtastic.serial_interface
import meshtastic.tcp_interface

parser = argparse.ArgumentParser(prog='MeshtasticMsg', add_help=True)
parser.add_argument('message', nargs='?',default='hello mesh', help='Message to send to the meshtastic channel if none Default=hello mesh')
parser.add_argument('channel', nargs='?',default='0', help='Channel to send message to, if none Default=0')
#args = parser.parse_args()
args = parser.parse_args(args=None if sys.argv[1:] else ['--help'])
xchannel = int(args.channel)

# By default will try to find a meshtastic device,
radio_hostname = "meshtastic.local" #Can also be an IP
interface = meshtastic.tcp_interface.TCPInterface(radio_hostname)
#interface = meshtastic.serial_interface.SerialInterface()
# interface = meshtastic.serial_interface.SerialInterface(devPath='/dev/cu.usbmodem53230050571')

#channelIndex should correspond to the message channel to use
print("sending " + (args.message) + " to channel " +(args.channel))
interface.sendText(args.message,channelIndex = xchannel)

interface.close()
